#List of slots to create or modify.
#See documentation for syntax: https://docs.illusivesoulworks.com/curios/configuration#slot-configuration
#
slots = ["id=charm;size=1;add_cosmetic=False", "id=hands;size=1;add_cosmetic=false", "id=belt;size=4;add_cosmetic=false"]

